version: '3.8'

services:
  eb1a-opportunity-system:
    build: .
    ports:
      - "5003:5003"
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - PORT=5003
      - FLASK_ENV=production
    volumes:
      - ./cache:/app/cache
      - ./src/database:/app/src/database
    restart: unless-stopped 